modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/modern-beta-fabric/issues"
license="MIT"

[[mods]]
modId="modern_beta"
version="${file.jarVersion}"
displayName="Modern Beta NeoForge"
displayURL="https://www.curseforge.com/minecraft/mc-mods/modern-beta-neoforge"
authors="bespectacled, bespectacled"
credits="SuperCoder7979, Arenovas, Amb0s, PaulEvs, comp500"
logoFile="icon.png"
description='''
Old world generation for modern Minecraft!
'''
[[dependencies.examplemod]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.examplemod]]
modId="neoforge"
type="required"
versionRange="[21.0.31-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="modern_beta.mixins.json"